export const GET_LATEST_POSTS = 'GET_LATEST_POSTS';
export const GET_POST_DATA = 'GET_POST_DATA';
export const GET_POST_COMMENTS = 'GET_POST_COMMENTS';

export const POST_NEW_POST = 'POST_NEW_POST';
export const POST_NEW_COMMENT = 'POST_NEW_COMMENT';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_COMMENT = 'DELETE_COMMENT';

export const SET_AVAILABLE_POST_DATA = 'SET_AVAILABLE_POST_DATA';
export const CLEAN_UP_CURRENT_POST = 'CLEAN_UP_CURRENT_POST';

// optional
// export const EDIT_POST = 'ADD_COMMENT';
