export const FETCH_LATEST_POSTS = 'FETCH_LATEST_POSTS';
export const FETCH_CURRENT_POST_DATA = 'FETCH_CURRENT_POST_DATA';
export const FETCH_CURRENT_POST_COMMENTS = 'FETCH_CURRENT_POST_COMMENTS';
export const WAIT_LATEST_POSTS_FETCHING = 'WAIT_LATEST_POSTS_FETCHING';
export const WAIT_CURRENT_POST_DATA_FETCHING = 'WAIT_CURRENT_POST_DATA_FETCHING';
export const WAIT_CURRENT_POST_COMMENTS_FETCHING = 'WAIT_CURRENT_POST_COMMENTS_FETCHING';

// optional
// export const ADD_NEW_POST = 'ADD_COMMENT';
// export const EDIT_POST = 'ADD_COMMENT';
