export const GET_POST_COMMENTS = 'GET_POST_COMMENTS';

export const POST_NEW_COMMENT = 'POST_NEW_COMMENT';
export const POST_NEW_SUB_COMMENT = 'POST_NEW_SUB_COMMENT';

export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_SUB_COMMENT = 'DELETE_SUB_COMMENT';
